# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "Wrangler": "01_wrangler.ipynb"}

modules = ["core.py",
           "wrangler.py"]

doc_url = "https://johnkabler.github.io/lasso/"

git_url = "https://github.com/johnkabler/lasso/tree/master/"

def custom_doc_links(name): return None
