# AUTOGENERATED! DO NOT EDIT! File to edit: 01_wrangler.ipynb (unless otherwise specified).

__all__ = ['Wrangler']

# Cell
from typing import Any, Dict

import boto3

class Wrangler:
    "Handler for deploying a docker image on one or more AWS EC2 Instances"
    def __init__(self):
        # TODO: We won't be able to use mfa.  Need to
        # have this take in access, secret, region
        # once escalated account is obtained for gitlab runner.
        self._ssm_client = boto3.client('ssm')

    def execute_command(self, instance_id: str, command: str) -> Dict[str, Any]:
        response = self._ssm_client.send_command(
            DocumentName="AWS-RunShellScript",
            Parameters={'commands': [command]},
            InstanceIds=[instance_id],
        )
        command_id = response["Command"]["CommandId"]
        instance_id = response["Command"]["InstanceIds"][0]

        return {
            "instance_id": instance_id,
            "command_id": command_id,
        }

    def get_commands(self, instance_id: str = None):
        if instance_id:
            return self._ssm_client.list_commands(InstanceId=instance_id)
        else:
            return self._ssm_client.list_commands()

    def get_command_status(self, instance_id: str, command_id: str):
        response = self._ssm_client.get_command_invocation(
            CommandId=command_id,
            InstanceId=instance_id,
        )
        return response['Status']